version: '2'
services:
    sampleapp-app:
        image: sampleapp
        external_links:
            - sampleapp-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=SampleApp
        ports:
            - 8080:8080
    sampleapp-mongodb:
        extends:
            file: mongodb.yml
            service: sampleapp-mongodb
